### ISSUE TITLE
Platzierung der hohen Bauteile

### ISSUE THREAD

**Issue by niklas26** [ToolboxPlane/PowerDeliveryBoard#1]
Optionen:
-Längeres Board
-höhere Pinnleisten
-?

**Comment by aul12** [comment]
Bin für längeres Board. Dann können in der überstehenden Fläche zusätzliche Schraublöcher angebracht werden und der komplette Stack einfach daran festgeschraubt werden und die Platinen müssen nicht nacheinander festgeschraubt werden
