### ISSUE TITLE
Outputs

### ISSUE THREAD

**Issue by ottojo** [ToolboxPlane/PowerDeliveryBoard#23]
Outputs needed:
XT60 for Motor
As many XT30 for 5V as reasonably fit on the board

**Comment by aul12** [comment]
On the expansion port a 5V rail is required as well (HC-SR04)

**Comment by ottojo** [comment]
Related: Find general purpose power connector for peripherals that only require power (FPV Cam, LEDs, ...)

**Comment by ottojo** [comment]
I propose using USB C for FC @aul12
